import time

lugares = ["Buenos Aires", "Madrid", "Londres", "Paris", "Roma"]
print(lugares)
time.sleep(1)
print(sorted(lugares))
time.sleep(1)
print(lugares)
time.sleep(1)
print(sorted((lugares),reverse=True))
time.sleep(1)
print(lugares)
time.sleep(1)
lugares.reverse()
print(lugares)
time.sleep(1)
lugares.reverse()
print(lugares)
time.sleep(1)
lugares.sort()
print(lugares)
time.sleep(1)
lugares.sort(reverse=True)
print(lugares)